export type {
  BaseMessage,
  BridgeMessage,
  HandshakeMessage,
  HeartbeatMessage,
  HeartbeatAckMessage,
  CommandMessage,
  CommandAckMessage,
  EventMessage,
  EventAckMessage,
  BatchMessage,
  BatchAckMessage,
  ErrorMessage,
  DisconnectMessage,
  CommandType,
  EventType,
  MessageType,
  ClientContext,
  BridgeConfig,
  ClientStatus,
  ServerStatus,
} from '../../shared/protocol.ts';
