import type { Session, ReportOptions } from './types.js';
import { formatMetadata } from './formatters/metadata.js';
import { summarizeInteractions } from './formatters/summary.js';
import { formatDetailedInteractions } from './formatters/interactions.js';
import { formatErrorDigests } from './formatters/errors.js';
import { formatStateSnapshots } from './formatters/snapshots.js';
import { formatAssets } from './formatters/assets.js';
import { allocateTokenBudget, trimRedundantLines } from './utils/token-aware.js';

export class ReportGenerator {
  constructor(private readonly session: Session) {}

  generate(options: ReportOptions = {}): string {
    const {
      includeAssets = false,
      maxTokens = 10000,
      trimRedundant = true,
      collapseLogs = true,
      collapseAssets = true,
    } = options;

    const budget = allocateTokenBudget(maxTokens);

    const sections: string[] = [];

    sections.push(formatMetadata(this.session.metadata));

    sections.push(
      summarizeInteractions(this.session.interactions, this.session.metadata.startTime)
    );

    sections.push(
      formatDetailedInteractions(this.session.interactions, budget.interactions, collapseLogs)
    );

    sections.push(formatErrorDigests(this.session.errors, budget.errors));

    sections.push(formatStateSnapshots(this.session.snapshots));

    if (includeAssets) {
      sections.push(formatAssets(this.session.interactions, collapseAssets));
    }

    sections.push(this.generateFooter());

    let report = sections.join('\n');

    if (trimRedundant) {
      report = trimRedundantLines(report);
    }

    return report;
  }

  private generateFooter(): string {
    return [
      '## Notes',
      '',
      '- This report was automatically generated by the Debug Recorder CLI.',
      '- Timestamps are in ISO 8601 format (UTC).',
      '- Token counts are approximate (4 chars ≈ 1 token).',
      '- PII data has been redacted unless explicitly included.',
      '',
      '_For more information, see: dev-tools/debug-recorder/README.md_',
      '',
    ].join('\n');
  }
}
